### ISSUE TITLE
Make edit params more consistent

### ISSUE THREAD

**Issue by ride90** [superdesk/video-server#17]
1) Crop
From `crop={ "height": 180, "width": 320, "x": 0, "y": 0 }` to `crop=0,0,320,180`.  For thumbnails and video editing.

2) Trim
From `"trim": { "start": 2, "end": 5 }` to `trim=2,5`

**Comment by idsvn** [comment]
We will enhancement in next PRs.

**Comment by idsvn** [comment]
`crop=0,0,320,180` isnot `json` format of payload, so we should change to string `"0,0,320,180"` or list `[0,0,320,180]`
